[workspace]

members = [
	"adm",
	"common",
	"dpd-client",
	"lldpd-client",
	"lldpd",
	"pcap",
	"xtask",
]

resolver = "2"

[workspace.dependencies]

# intra-package dependencies
dpd-client = { path = "dpd-client" }
lldpd-client = { path = "lldpd-client" }
common = { path = "common" }
pcap = { path = "pcap" }

# oxide dependencies from github
crucible-smf = { git = "https://github.com/oxidecomputer/crucible", rev = "9bcd80c3392d2f0128ef1ac5aa13036d268a8e8e" }
progenitor = { git = "https://github.com/oxidecomputer/progenitor", branch = "main"}
omicron-zone-package = "0.7.1"

# public dependencies from crates.io
anyhow = "1.0"
bytes = "1.0"
chrono = "0.4"
colored = "2"
dropshot = "0.10.0"
futures = "0.3"
http = "0.2.9"
rand = "0.8"
regex = "1.7.3"
reqwest = "0.11"
schemars = "0.8"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3"
signal-hook-tokio = { version = "0.3", features = [ "futures-v0_3" ] }
slog = { version = "2.7", features = [ "release_max_level_debug", "max_level_trace" ] }
slog-async = "2.6"
slog-bunyan = "2.4"
slog-term = "2.6"
structopt = "0.3"
socket2 = { version = "0.5", features = ["all"] }
tabwriter = { version = "1", features = ["ansi_formatting"] }
thiserror = "1.0"
tokio = { version = "1.24", features = ["full"]}
