[package]
name = "protocol"
version = "0.1.0"
authors = ["Nils Nieuwejaar <nils@oxide.computer>"]
edition = "2021"

[dependencies]
anyhow.workspace = true
serde.workspace = true
schemars.workspace = true
thiserror.workspace = true
