[package]
name = "lldpd-types"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
chrono.workspace = true
protocol.workspace = true
schemars.workspace = true
serde.workspace = true
uuid.workspace = true
