#!/sbin/sh

. /lib/svc/share/smf_include.sh

ROOT=/opt/oxide/dendrite

if /usr/bin/pgrep -x -u 0 lldpd >/dev/null 2>&1; then
	echo "$0: lldpd is already running"
	exit $SMF_EXIT_ERR_NOSMF
fi

${ROOT}/bin/lldpd run &

exit $SMF_EXIT_OK
