[package]
name = "pcap"
version = "0.1.0"
authors = ["Nils Nieuwejaar <nils@oxide.computer>"]
edition = "2021"
build = "build.rs"

[dependencies]
thiserror.workspace = true

[build-dependencies]
cc = "1.0"
bindgen = "0.64"
